//模块1 柱状图
(function(){
  var myChart=echarts.init(document.querySelector(".bar .chart"));
  var option={
    color:["#2f89cf"],
    // title:{
    //   text:"传感器数量"
    // },
    grid:{
      left:"0%",
      right:"0%",
      top:"10px",
      bottom:"4%",
      containLabel:true
    },
    tooltip:{
      trigger:"axis",
    },
    xAxis:{
      type:"category",
      data:["倾角计","位移绳","位移计","智能传感","水位计","沉降仪"],
      //修改刻度标签相关样式（即x轴数字样式）
      axisLabel:{
        color:"rgba(255,255,255,.6)",
        fontSize:"12px"
      },
      axisLine:{
        show:false
      }
    },
    yAxis:{
      type:"value",
      axisLabel:{
        color:"rgba(255,255,255,.6)",
        fontSize:"12px",
      },
      //y轴线条的样式
      axisLine:{
        lineStyle:{
          color:"rgba(255,255,255,.1)",
          width:2
        }
      },
      //y轴分割线的样式
      splitLine:{
        lineStyle:{
          color:"rgba(255,255,255,.1)"
        }
      }
    },
    series:[{
      name:"数量",
      type:"bar",
      barWidth:"35%", //修改柱状图的条形框的宽度
      data:[5,20,36,10,10,20],
      //将柱状图的柱子修改为圆角
      itemStyle:{
        barBorderRadius:5
      }
    }]
  };
  myChart.setOption(option);

  //!!!!!让图表跟随屏幕自适应
  window.addEventListener("resize",function(){
    myChart.resize();
  });
})();

//横行柱状图
(function(){
  var myColors=["#1089E7","#F57474","#56D0E3","#F8B448","#8B78F6","#05F834"];
  var myChart=echarts.init(document.querySelector(".bar3 .chart"));
  var option={
    tooltip:{
      trigger:'axis',
      axisPointer:{
        type:"shadow"
      }
    },
    grid:{
      top:"10%",
      left:"22%",
      bottom:"10%",
      //containLabel:true
    },
    //不显示x轴的相关信息
    xAxis:{
      show:false
    },
    yAxis:[{
      type:"category",
      data:["倾角计","位移绳","位移计","智能传感","水位计","沉降仪"],
      inverse:true,
      //不显示y轴线条
      axisLine:{
        show:false
      },
      //不显示刻度
      axisTick:{
        show:false
      },
      //修改y轴的文字颜色
      axisLabel:{
        color:"#fff"
      }
    },{
      type:"category",
      data:[5,20,36,10,10,20],
      inverse:true,
      //不显示y轴线条
      axisLine:{
        show:false
      },
      //不显示刻度
      axisTick:{
        show:false
      },
      //修改y轴的文字颜色
      axisLabel:{
        color:"#fff"
      }
    }],
    series:[{
      name:"正常设备",
      type:"bar",
      data:[5,20,36,10,10,20],
      yAxisIndex:0,
      itemStyle:{
        normal:{
          barBorderRadius:20,
          //设置柱子多种颜色
          color:function(params){
            return myColors[params.dataIndex];
          }
        }
      },
      barCategoryGap:50,
      barWidth:15,
      //显示柱子内的文字
      label:{
        show:true,
        position:"inside",
        formatter:"{c}%"
      }
    },
    {
      name:"设备总数",
      type:"bar",
      data:[10,32,40,11,10,25],
      yAxisIndex:1,
      barCategoryGap:50,
      barWidth:15,
      itemStyle:{
        color:"none",
        borderColor:"#00c1de",
        borderWidth:3,
        barBorderRadius:15
      }
    }
  ]
  }

  myChart.setOption(option);

  //适应屏幕大小
  window.addEventListener("resize",function(){
    myChart.resize();
  })
})()